mysite/application/urls.py
from django.urls import re_path, include
from . import views
from django.views.generic import ListView, DetailView
from django.contrib.auth.views import PasswordResetView


from .models import CustomUser, notes
from .views import RegisterUser, AuthUser, LogOutUser, NoteUpdate, NoteCreate, NoteDelete

urlpatterns= [

    re_path(r'^$', views.index, name = 'index'),

    re_path(r'^add-note/$', NoteCreate.as_view(), name = 'add_note'),
    re_path(r'^update-note/(?P<pk>\d+)/$', NoteUpdate.as_view(), name = 'update_note'),
    re_path(r'^delete-note/(?P<pk>\d+)/$', NoteDelete.as_view(), name = 'delete_note'),
    

    #listing a special page for the unique note
    re_path(r'^(?P<pk>\d+)/$', DetailView.as_view(model=notes, template_name ="application/note.html")),

    #register
    re_path(r'^register/$', RegisterUser.as_view(), name = 'register'),

    #auth
    re_path(r'^auth/$', AuthUser.as_view(template_name='application/login.html'), name = 'login'),

    #password reset
    re_path(r'^password-reset/$', PasswordResetView.as_view(template_name=''), name='password_reset' ),

    re_path(r'^logout/$', LogOutUser.as_view(), name = 'logout'),
    re_path(r'^contact/$', ListView.as_view(model=notes, template_name = "application/contact_us.html"), name="contact"),
]

mysite/mysite/urls.py
from django.urls import re_path, include
from django.contrib import admin

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path('^', include('application.urls')),
]

mysite/application/models.py
from django.db import models
from datetime import date
from django.contrib.auth.models import AbstractUser
from django.utils.translation import ugettext_lazy as _
from .managers import CustomUserManager
from django.conf import settings

class CustomUser(AbstractUser):
    username = None
    email = models.EmailField(_('email address'), unique=True)
    status = models.CharField(max_length = 140)
    biography = models.TextField()
    birth_date = models.DateField(default=date.today)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    objects = CustomUserManager()
    def __str__(self):
        return self.email

class notes(models.Model):
    date = models.DateTimeField()
    title = models.CharField(max_length = 255)
    text = models.TextField()
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    def __unicode__(self):
        return self.title

    

mysite/application/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm
from .models import CustomUser, notes

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('email',)

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ('email',)

#register
class RegisterUserForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['email', 'biography', 'birth_date']

#auth
class PickyAuthenticationForm(AuthenticationForm):
    def confirm_login_allowed(self, CustomUser):
        if not CustomUser.is_active:
            raise ValidationError(
                _("This account is inactive."),
                code='inactive',
            )

class NoteCreateForm(forms.ModelForm):

    class Meta:
        model = notes
        fields = ['date', 'title', 'text']
    
    #def init(self, *args, **kwargs):
    #    super(NoteCreateForm, self).init(*args, **kwargs)
    #    self.instance.author = self.request.user
     #         #  CustomUser.object.filter(email = self.request.user)[0]



class NoteUpdateForm(forms.ModelForm):
   # title = forms.CharField(max_length = 255)
    #text = forms.CharField(widget=forms.Textarea)
    class Meta:
        model = notes
        fields = ['title', 'text']

class NoteDeleteForm(forms.ModelForm):
    class Meta:
        model = notes
        fields = ['date', 'title', 'text','author']

mysite/application/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth import login as auth_login

from django.template import RequestContext

from django.shortcuts import render, redirect, resolve_url
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.contrib.auth.views import LoginView, LogoutView

from django.core.paginator import Paginator #pagination
from django.urls import reverse_lazy

from django.http import HttpRequest

from django.conf import settings

from .models import CustomUser, notes
from .forms import RegisterUserForm, PickyAuthenticationForm, NoteCreateForm, NoteDeleteForm, NoteUpdateForm
# Create your views here.

class BaseView():
    user = None
    blog_user = None

    def dispatch(self, request, *args, **kwargs):
        self.object = super(BaseView, self).get_object()
        if not request.user.is_anonymous and self.object.author == request.user:
           self.blog_user = request.user
           return super(BaseView, self).dispatch(request, *args, **kwargs)
        elif request.user.is_anonymous:
            return render(request, 'application/login_error.html')
        elif self.object.author != request.user:
            print(request)
            return render(request, 'application/not_author_error.html')
       

    def get_context_data(self, **kwargs):
        context = super(BaseView, self).get_context_data(**kwargs)
        context['context_user'] = self.user
        context['blog_user'] = self.blog_user
        context['request'] = self.request
        return context

def index(request):
    user_display = CustomUser.objects.all()
    notes_display = notes.objects.all().order_by("-date")

    notes_paginator = Paginator(notes_display, 20) # Show 20 articles per page.

    page_number = request.GET.get('page', 1)
    page_obj = notes_paginator.get_page(page_number)

    is_paginated = page_obj.has_other_pages()

    if page_obj.has_previous():
        prev_url = '?page={}'.format(page_obj.previous_page_number())
    else:
        prev_url = ''
    
    if page_obj.has_next():
        next_url = '?page={}'.format(page_obj.next_page_number())
    else:
        next_url = ''
    
    context = {
        'Users': user_display,
        'notes': page_obj,
        'is_paginated': is_paginated,
        'next_url': next_url,
        'prev_url': prev_url
    }

    return render(request, 'application/homePage.html', context = context)

class RegisterUser(CreateView):
    model = CustomUser
    form_class = RegisterUserForm
    template_name = "application/user_register.html"
    def form_valid(self, form):
        
        form.save()
        return redirect("/")
        
    def get_success_url(self):
        if self.success_url:
            return self.success_url.format(**self.object.__dict__)
        else:
            raise ImproperlyConfigured(
                "No URL to redirect to. Provide a success_url.")


class AuthUser(LoginView):
    form_class = PickyAuthenticationForm
    template_name = 'application/login.html'
    
    def form_valid(self, form):
        """Security check complete. Log the user in."""
        auth_login(self.request, form.get_user())
        return HttpResponseRedirect(self.get_success_url())
    
    def get_success_url(self):
        url = self.get_redirect_url()
        return url or resolve_url(settings.LOGIN_REDIRECT_URL)
    

class NoteCreate(CreateView, FormView):
    model = notes
    form_class = NoteCreateForm
    template_name = "application/note_form.html"

    def form_valid(self, form):
        if self.request.user.is_authenticated:
            form.instance.author = self.request.user
            form.save()
            return redirect("/")
        else: 
            return render(request, 'application/login_error.html')

    def success_url(self):
        return redirect("/")

class NoteUpdate(BaseView, UpdateView):
    model = notes
    form_class = NoteUpdateForm
    template_name = "application/note_update_form.html"

    def form_valid(self, form):
        form.save()
        return redirect("/")

    def get_success_url(self):
        return redirect("/")


class NoteDelete(BaseView,DeleteView):
    model = notes
    success_url = reverse_lazy('index')
    form_class = NoteDeleteForm
    template_name = 'application/note_delete_form.html'

    def delete(self, request, *args, **kwargs):
        """
        Call the delete() method on the fetched object and then redirect to the
        success URL.
        """
        self.object.delete()
        return HttpResponseRedirect(self.success_url)
    
    def get_success_url(self):
        if self.success_url:
            return self.success_url.format(**self.object.__dict__)
        else:
            raise ImproperlyConfigured(
                "No URL to redirect to. Provide a success_url.")

#logout
class LogOutUser(LogoutView):
    template_name = 'application/logout.html'

mysite/application/templates/application/contact_us.html
{% extends "application/wrapper.html" %}

{% load static %}
{% block head %}

  <!-- Site Properties -->
  <link rel="stylesheet" type="text/css" href= "{% static 'fomantic-ui-dir/semantic/dist/components/reset.css' %}">
  <link rel="stylesheet" type="text/css" href= "{% static 'fomantic-ui-dir/semantic/dist/components/site.css' %}">

  <link rel="stylesheet" type="text/css" href= "{% static 'fomantic-ui-dir/semantic/dist/components/container.css' %}">
  <link rel="stylesheet" type="text/css" href= "{% static 'fomantic-ui-dir/semantic/dist/components/grid.css' %}"> 
  <link rel="stylesheet" type="text/css" href= "{% static 'fomantic-ui-dir/semantic/dist/components/header.css' %}">
  <link rel="stylesheet" type="text/css" href= "{% static 'fomantic-ui-dir/semantic/dist/components/image.css' %}">
  <link rel="stylesheet" type="text/css" href= "{% static 'fomantic-ui-dir/semantic/dist/components/menu.css' %}">

  <link rel="stylesheet" type="text/css" href= "{% static 'fomantic-ui-dir/semantic/dist/components/divider.css' %}">
  <link rel="stylesheet" type="text/css" href= "{% static 'fomantic-ui-dir/semantic/dist/components/segment.css' %}">
  <link rel="stylesheet" type="text/css" href= "{% static 'fomantic-ui-dir/semantic/dist/components/form.css' %}">
  <link rel="stylesheet" type="text/css" href= "{% static 'fomantic-ui-dir/semantic/dist/components/input.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'fomantic-ui-dir/semantic/dist/components/button.css' %}">
  <link rel="stylesheet" type="text/css" href= "{% static 'fomantic-ui-dir/semantic/dist/components/list.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'fomantic-ui-dir/semantic/dist/components/message.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'fomantic-ui-dir/semantic/dist/components/icon.css' %}">

  
  <link  rel="stylesheet" type="text/css" href= "{% static './fomantic-ui-dir/semantic/dist/components/form.css' %}">
  <link  rel="stylesheet" type="text/css" href= "{% static './fomantic-ui-dir/semantic/dist/components/transition.css' %}">

  <style type="text/css">
    body {
      background-color: #DADADA;
    }
    body > .grid {
      height: 100%;
    }
    .image {
      margin-top: -100px;
    }
    .column {
      max-width: 450px;
    }
  </style>
  <script>
    $(document)
      .ready(function() {
        $('.ui.form')
          .form()
        ;
      })
    ;
    </script>

{% endblock%}

{% block content %}


<div class="ui segment">
    <div class="ui basic modal">
      <div class="content">
        <h2 class="ui inverted header">Email: petya205.205@mail.ru</h2>
        <h2 class="ui inverted header">Телефон: 89134385322</h2>
      </div>
    </div>
  </div>

  <script>
    $('.ui.basic.modal')
      .modal("show")
    ;
    var dimmed = document.getElementsByTagName("body"); 
    dimmed = Array.from(dimmed);
    //console.log(dimmed[0].className);
    $('body').click(function(){
      if (dimmed[0].className == 'dimmable dimmed'){ 
        location.href = "/";
      }
    });
  </script>

{% endblock %}

mysite/application/templates/application/login.html
{% extends "application/wrapper.html" %}

{% load static %}
{% block head %}

  <!-- Site Properties -->
  <link rel="stylesheet" type="text/css" href= "{% static 'fomantic-ui-dir/semantic/dist/components/reset.css' %}">
  <link rel="stylesheet" type="text/css" href= "{% static 'fomantic-ui-dir/semantic/dist/components/site.css' %}">

  <link rel="stylesheet" type="text/css" href= "{% static 'fomantic-ui-dir/semantic/dist/components/container.css' %}">
  <link rel="stylesheet" type="text/css" href= "{% static 'fomantic-ui-dir/semantic/dist/components/grid.css' %}"> 
  <link rel="stylesheet" type="text/css" href= "{% static 'fomantic-ui-dir/semantic/dist/components/header.css' %}">
  <link rel="stylesheet" type="text/css" href= "{% static 'fomantic-ui-dir/semantic/dist/components/image.css' %}">
  <link rel="stylesheet" type="text/css" href= "{% static 'fomantic-ui-dir/semantic/dist/components/menu.css' %}">

  <link rel="stylesheet" type="text/css" href= "{% static 'fomantic-ui-dir/semantic/dist/components/divider.css' %}">
  <link rel="stylesheet" type="text/css" href= "{% static 'fomantic-ui-dir/semantic/dist/components/segment.css' %}">
  <link rel="stylesheet" type="text/css" href= "{% static 'fomantic-ui-dir/semantic/dist/components/form.css' %}">
  <link rel="stylesheet" type="text/css" href= "{% static 'fomantic-ui-dir/semantic/dist/components/input.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'fomantic-ui-dir/semantic/dist/components/button.css' %}">
  <link rel="stylesheet" type="text/css" href= "{% static 'fomantic-ui-dir/semantic/dist/components/list.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'fomantic-ui-dir/semantic/dist/components/message.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'fomantic-ui-dir/semantic/dist/components/icon.css' %}">

  
  <link  rel="stylesheet" type="text/css" href= "{% static './fomantic-ui-dir/semantic/dist/components/form.css' %}">
  <link  rel="stylesheet" type="text/css" href= "{% static './fomantic-ui-dir/semantic/dist/components/transition.css' %}">

  <style type="text/css">
    body {
      background-color: #DADADA;
    }
    body > .grid {
      height: 100%;
    }
    .image {
      margin-top: -100px;
    }
    .column {
      max-width: 450px;
    }
  </style>
  <script>
  $(document)
    .ready(function() {
      $('.ui.form')
        .form({
          fields: {
            username: {
              identifier  : 'username',
              rules: [
                {
                  type   : 'empty',
                  prompt : 'Please enter your e-mail'
                },
                {
                  type   : 'email',
                  prompt : 'Please enter a valid e-mail'
                }
              ]
            },
            password: {
              identifier  : 'password',
              rules: [
                {
                  type   : 'empty',
                  prompt : 'Please enter your password'
                },
                {
                  type   : 'length[6]',
                  prompt : 'Your password must be at least 6 characters'
                }
              ]
            }
          }
        })
      ;
    })
  ;
  </script>
{% endblock %}



{% block content %}

{% if form.errors %}
<div class = 'ui middle aligned center aligned grid'>
  <div class = 'column'>
      <h2 class = 'ui image header'>Авторизация</h2>
      <form class="ui large form error" method="post" action="{% url 'login' %}">
      {% csrf_token %}
      <div class='ui stacked segment'>
          <div class ='field error'>
              <div class='ui left icon input'>
                  <i class = 'user icon'></i>
                  <input type="text" name="username" placeholder="E-mail адрес"> 
              </div>
          </div>
          <div class ='field error'>
              <div class='ui left icon input'>
                  <i class = 'lock icon'></i>
                  <input  type="password" name="password" placeholder="Пароль"> 
              </div>
          </div>
      <div class="ui error message"></div>
      
          
      </div>
      <div class="ui fluid large submit black button">Войти</div>
      <input type="hidden" name="next" value="{{ next }}">

      
      </form> 

    
  </div>
</div>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Пожалуйста, авторизуйтесь, чтобы видеть данный пост.</p>
    {% endif %}
{% endif %}
<div class = 'ui middle aligned center aligned grid'>
    <div class = 'column'>
        <h2 class = 'ui image header'>Авторизация</h2>
        <form class="ui large form" method="post" action="{% url 'login' %}">
        {% csrf_token %}
        <div class='ui stacked segment'>
            <div class ='field'>
                <div class='ui left icon input'>
                    <i class = 'user icon'></i>
                    <input type="text" name="username" placeholder="E-mail адрес"> 
                </div>
            </div>
            <div class ='field'>
                <div class='ui left icon input'>
                    <i class = 'lock icon'></i>
                    <input type="password" name="password" placeholder="Пароль"> 
                </div>
            </div>
        
        
            
        </div>
        <div class="ui fluid large submit black button">Войти</div>
        <input type="hidden" name="next" value="{{ next }}">

        <div class="ui error message"></div>
        </form>

        
    </div>
</div>
{% endblock %}

mysite/application/templates/application/logout.html
{% extends "application/wrapper.html" %}

{% block content %}


{% endblock %}

mysite/application/templates/application/note.html
{% extends "application/wrapper.html" %}

{% block content %}
<div class="ui modal">
    <h2 class="text-info">{{notes.title}}</h2>
    <h3 class="text-info">{{notes.date }}</h3>
    <p>Текст блога: <br></p>
    <p>{{notes.text}}</p>
</div>
    <script>
    $('.ui.modal')
        .modal('show')
    ;
    
    </script>
{% endblock %}

mysite/application/templates/application/note_form.html
{% extends "application/wrapper.html" %}

{% load static %}
{% block head %}

  <!-- Site Properties -->
  <link rel="stylesheet" type="text/css" href= "{% static 'fomantic-ui-dir/semantic/dist/components/reset.css' %}">
  <link rel="stylesheet" type="text/css" href= "{% static 'fomantic-ui-dir/semantic/dist/components/site.css' %}">

  <link rel="stylesheet" type="text/css" href= "{% static 'fomantic-ui-dir/semantic/dist/components/container.css' %}">
  <link rel="stylesheet" type="text/css" href= "{% static 'fomantic-ui-dir/semantic/dist/components/grid.css' %}"> 
  <link rel="stylesheet" type="text/css" href= "{% static 'fomantic-ui-dir/semantic/dist/components/header.css' %}">
  <link rel="stylesheet" type="text/css" href= "{% static 'fomantic-ui-dir/semantic/dist/components/image.css' %}">
  <link rel="stylesheet" type="text/css" href= "{% static 'fomantic-ui-dir/semantic/dist/components/menu.css' %}">

  <link rel="stylesheet" type="text/css" href= "{% static 'fomantic-ui-dir/semantic/dist/components/divider.css' %}">
  <link rel="stylesheet" type="text/css" href= "{% static 'fomantic-ui-dir/semantic/dist/components/segment.css' %}">
  <link rel="stylesheet" type="text/css" href= "{% static 'fomantic-ui-dir/semantic/dist/components/form.css' %}">
  <link rel="stylesheet" type="text/css" href= "{% static 'fomantic-ui-dir/semantic/dist/components/input.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'fomantic-ui-dir/semantic/dist/components/button.css' %}">
  <link rel="stylesheet" type="text/css" href= "{% static 'fomantic-ui-dir/semantic/dist/components/list.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'fomantic-ui-dir/semantic/dist/components/message.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'fomantic-ui-dir/semantic/dist/components/icon.css' %}">

  <link  rel="stylesheet" type="text/css" href= "{% static './fomantic-ui-dir/semantic/dist/components/form.css' %}">
  <link  rel="stylesheet" type="text/css" href= "{% static './fomantic-ui-dir/semantic/dist/components/transition.css' %}">

  <style type="text/css">
    body {
      background-color: #DADADA;
    }
    body > .grid {
      height: 100%;
    }
    .image {
      margin-top: -100px;
    }
    .column {
      max-width: 450px;
    }
  </style>
  <script>
  $(document)
    .ready(function() {
      $('.ui.form')
        .form({
          fields: {
            date: {
              identifier  : 'date',
              rules: [
                {
                  type   : 'empty',
                  prompt : 'Please enter today date '
                }
              ]
            },
            title: {
              identifier  : 'title',
              rules: [
                {
                  type   : 'empty',
                  prompt : 'Please enter title of your article'
                }
              ]
            },
            text: {
              identifier  : 'text',
              rules: [
                {
                  type   : 'empty',
                  prompt : 'Please enter text of the article '
                }
              ]
            },
          }
        })
      ;
    })
  ;
  </script>
{% endblock %}




{% block content %}
{% if request.user.is_authenticated %}
<div class = 'ui middle aligned center aligned grid'>
    <div class = 'column'>
        <h2 class = 'ui image header'>Новый пост</h2>
        <form class="ui large form" method="post">
            {% csrf_token %}
            
            <div class ='field'>
                <input type="text" name="date" required id="id_date" placeholder="Дата. Пример: yyyy-mm-dd">
            </div>
            <div class ='field'>
                <input type="text" name="title" maxlength="128" required id="id_title" placeholder="Заголовок">
            </div>
            <div class ='field'>
                <textarea name="text" cols="40" rows="10" required id="id_text" placeholder="Текст поста"></textarea>
            </div>
        
            <div class="ui fluid large submit black button">Запостить</div>
            <input type="hidden" name="next" value="{{ next }}">

            <div class="ui error message"></div>
        
        </form>
    </div>
</div>
{% else %}
<div class="ui segment">
    <div class="ui basic modal">
      <div class="content">
        <h2 class="ui inverted header">Пожалуйста, авторизуйтесь, чтобы видеть данный пост.</h2>
        <a class="ui button" href="{% url 'login' %}">Войти</a>
      </div>
    </div>
  </div>

  <script>
    $('.ui.basic.modal')
      .modal('show')
    ;
    
      </script>
{% endif %}
{% endblock %}

mysite/application/templates/application/user_register.html
{% extends "application/wrapper.html" %}

{% load static %}
{% block head %}

<link rel="stylesheet" type="text/css" href= "{% static 'fomantic-ui-dir/semantic/dist/components/reset.css' %}">
  <link rel="stylesheet" type="text/css" href= "{% static 'fomantic-ui-dir/semantic/dist/components/site.css' %}">

  <link rel="stylesheet" type="text/css" href= "{% static 'fomantic-ui-dir/semantic/dist/components/container.css' %}">
  <link rel="stylesheet" type="text/css" href= "{% static 'fomantic-ui-dir/semantic/dist/components/grid.css' %}"> 
  <link rel="stylesheet" type="text/css" href= "{% static 'fomantic-ui-dir/semantic/dist/components/header.css' %}">
  <link rel="stylesheet" type="text/css" href= "{% static 'fomantic-ui-dir/semantic/dist/components/image.css' %}">
  <link rel="stylesheet" type="text/css" href= "{% static 'fomantic-ui-dir/semantic/dist/components/menu.css' %}">

  <link rel="stylesheet" type="text/css" href= "{% static 'fomantic-ui-dir/semantic/dist/components/divider.css' %}">
  <link rel="stylesheet" type="text/css" href= "{% static 'fomantic-ui-dir/semantic/dist/components/segment.css' %}">
  <link rel="stylesheet" type="text/css" href= "{% static 'fomantic-ui-dir/semantic/dist/components/form.css' %}">
  <link rel="stylesheet" type="text/css" href= "{% static 'fomantic-ui-dir/semantic/dist/components/input.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'fomantic-ui-dir/semantic/dist/components/button.css' %}">
  <link rel="stylesheet" type="text/css" href= "{% static 'fomantic-ui-dir/semantic/dist/components/list.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'fomantic-ui-dir/semantic/dist/components/message.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'fomantic-ui-dir/semantic/dist/components/icon.css' %}">

  
  <link  rel="stylesheet" type="text/css" href= "{% static './fomantic-ui-dir/semantic/dist/components/form.css' %}">
  <link  rel="stylesheet" type="text/css" href= "{% static './fomantic-ui-dir/semantic/dist/components/transition.css' %}">
<style type="text/css">
    body {
      background-color: #DADADA;
    }
    body > .grid {
      height: 100%;
    }
    .image {
      margin-top: -100px;
    }
    .column {
      max-width: 450px;
    }
  </style>

<script>
  $(document)
    .ready(function() {
      $('.ui.form')
        .form({
          fields: {
            email: {
              identifier  : 'email',
              rules: [
                {
                  type   : 'empty',
                  prompt : 'Please enter your e-mail'
                }
              ]
            },
            biography: {
              identifier  : 'biography',
              rules: [
                {
                  type   : 'empty',
                  prompt : 'Please enter your biography'
                }
              ]
            },
            birth_date: {
              identifier  : 'birth_date',
              rules: [
                {
                  type   : 'empty',
                  prompt : 'Please enter your birth date'
                }
              ]
            },
            password1: {
              identifier  : 'password1',
              rules: [
                {
                  type   : 'empty',
                  prompt : 'Please enter your password'
                },
                {
                  type   : 'length[6]',
                  prompt : 'Your password must be at least 6 characters'
                }
              ]
            },
            password2: {
              identifier  : 'password2',
              rules: [
                {
                  type   : 'empty',
                  prompt : 'Please enter your password confirmation'
                }
              ]
            }
            
          }
        })
      ;
    })
  ;
  </script>

{% endblock %}

{% block content %}
<div class = 'ui middle aligned center aligned grid'>
    <div class = 'column'>
        <h2 class = 'ui image header'>Регистрация</h2>
          <form class='ui large form' method="post" action="{% url 'register' %}">
            {% csrf_token %}
            <div class='ui stacked segment'>
                <div class ='field'>
                    <input type="email" name="email" maxlength="254" autofocus required id="id_email" placeholder="E-mail адрес">
                </div>
                <div class ='field'>
                    <textarea name="biography" cols="40" rows="10" required id="id_biography" placeholder="Иная информация"></textarea>
                </div>
                <div class ='field'>
                    <input type="text" name="birth_date" required id="id_birth_date" placeholder="Дата рождения. Пример: yyyy-mm-dd">
                </div>
                <input type="hidden" name="initial-birth_date" value="2021-04-30" id="initial-id_birth_date">
                <div class ='field'>
                    <input type="password" name="password1" autocomplete="new-password" required id="id_password1" placeholder="Пароль">
                </div>

                <span class="helptext">
                    <ul>
                        <li>Пароль не может быть слишком похож на ваш логин.</li>
                        <li>Пароль должен содержать минимум 8 знаков.</li>
                        <li>Пароль не должен быть простым.</li>
                        <li>Пароль не может состоять только из цифр.</li>
                    </ul>
                </span>
                <div class ='field'>
                    <input type="password" name="password2" autocomplete="new-password" required id="id_password2" placeholder="Подтверждение пароля">
                </div>
            </div>
            <div class='ui fluid large submit black button'>Зарегистрироваться</div>
            <input type="hidden" name="next" value="{{ next }}">

            <div class="ui error message"></div>
          </form>
    </div>
</div>


{% endblock %}